### ISSUE TITLE
consolidation - failed to get shared write lock

### ISSUE THREAD

**Issue by MaxiReglisse** [dguerri/LibVirtKvm-scripts#45] opened 2019-07-30 16:32 UTC
Consolidation was working perfectly with Ubuntu 16.04, but it fails with Ubuntu 18.04. 
The problem is the new version, QEMU 2.10 comes with enabled builtin file locking to prevent image corruption, as explained [here](https://github.com/OpenNebula/one/issues/1449)

The error message is:

    [DEB] Getting all backing files for: '/var/lib/libvirt/images/salinois.bimg-20190728-115225'
    qemu-img: Could not open '/var/lib/libvirt/images/salinois.bimg-20190728-115225': Failed to get shared "write" lock
    Is another process using the image?

i do not see what i can do to solve the problem...

**Comment by AJRepo** [comment] 2019-07-31 16:11
This is caused by issue: https://bugs.launchpad.net/qemu/+bug/1721788 with qemu-img not reporting information without the --force-share flag. 

A quick workaround that fixes this issue is to change fi-backup to add the  "--force-share" flag right after the qemu-img "info" command as follows
```
@@ -190,7 +190,7 @@ function get_backing_file() {
    local _ret=
    local _backing_file=
 
-   _backing_file=$($QEMU_IMG info "$file_name" | \
+   _backing_file=$($QEMU_IMG info --force-share "$file_name" | \
       awk '/^backing file: / {$1=$2=""; print $0}'|sed 's/^[ \t]*//')
    _ret=$?
```

Before fixing it in fi-backup, in this repo, we should look to see at what version --force-share was introduced so that fi-backup doesn't add the flag and possibly break an older version of qemu-img

**Comment by AJRepo** [comment] 2019-07-31 19:47
Fixed with 618617275d62bd26be7645bf33632cdcc8b33ed3 

TravisCI build needed to be updated given their recent changes so fixed those as well through 9d7801f904ceccd03a923668a40cb77d5169a358

**Closed by AJRepo** 2019-07-31 19:47 UTC

**Comment by MaxiReglisse** [comment] 2019-08-01 12:42
it solved my problem, many thanks!
a question: do you think that the use of the virtual machine lock manager would be a more sustainable solution?
[virtlock](https://libvirt.org/locking-lockd.html) or [sanlock](https://libvirt.org/locking-sanlock.html)... but i do not know how to do that...

**Comment by AJRepo** [comment] 2019-09-08 00:43
No. Here's why

1) A machine which replicated this issue had virtlockd enabled and running. 

2) The command that's failing was `"qemu_img info"` which is just getting info (names, paths) about the VM's disk(s) (backing files) - not actually modifying it yet. 

3) These locking programs are designed to be able to expand for cross-host disk management when you might have multiple machines possibly handling one VM. There's still locking, 

So ... no - I don't think virtlock/sanlock  will solve your problem.
